name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:

  scan-terraform:
    permissions: write-all
    name: Scan Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Scan Terraform
        uses: gautambaghel/sarif-to-terraform-runtask@1.0.0-beta
        with:
          ngrok_domain: ${{ secrets.NGROK_DOMAIN }}
          ngrok_authtoken: ${{ secrets.NGROK_TOKEN }}

      - uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.4
        name: Run Terraform Workspace
        id: run
        continue-on-error: true
        with:
          plan_only: true
          organization: 'tfc-integration-sandbox'
          workspace: 'vulnerable-ec2'
          token: ${{ secrets.TFC_API_TOKEN }}

      - run: cat terraform-scanner-runtask-action.log
        name: Scan log results

      - name: Upload scan results to GitHub UI
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
